// High-quality food images from Unsplash
const FOOD_IMAGES = {
  bruschetta: "https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80",
  calamari: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80",
  mushroom_soup: "https://images.unsplash.com/photo-1547592166-23ac45744acd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80",
  steak: "https://images.unsplash.com/photo-1600891964092-4316c288032e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80",
  salmon: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80",
  risotto: "https://images.unsplash.com/photo-1633964913849-96cdfdc1bfe6?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80",
  pasta: "https://images.unsplash.com/photo-1563379926898-05f4575a45d8?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80",
  chocolate_cake: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80",
  creme_brulee: "https://images.unsplash.com/photo-1470124182917-cc6e71b22ecc?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80",
  martini: "https://images.unsplash.com/photo-1575023782549-62ca0d244b39?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80",
  lemonade: "https://images.unsplash.com/photo-1621263764928-df1444c5e859?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80",
  sushi: "https://images.unsplash.com/photo-1611143669185-af224c5e3252?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80",
  burrata: "https://images.unsplash.com/photo-1626099470327-a90b4e7e23ab?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80",
  tiramisu: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80",
  cocktail: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80",
  salad: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80",
};

// Categories with icons
export const categories = [
  { id: 'all', name: 'All Menu', icon: 'menu' },
  { id: 'starters', name: 'Starters', icon: 'soup' },
  { id: 'mains', name: 'Main Courses', icon: 'utensils' },
  { id: 'desserts', name: 'Desserts', icon: 'cake' },
  { id: 'drinks', name: 'Drinks', icon: 'wine' },
  { id: 'seasonal', name: 'Seasonal', icon: 'calendar' },
];

// Dietary options with icons
export const dietaryOptions = [
  { id: 'vegetarian', name: 'Vegetarian', icon: 'leaf' },
  { id: 'vegan', name: 'Vegan', icon: 'sprout' },
  { id: 'gluten-free', name: 'Gluten Free', icon: 'wheat-off' },
  { id: 'dairy-free', name: 'Dairy Free', icon: 'milk-off' },
  { id: 'nut-free', name: 'Nut Free', icon: 'nut-off' },
  { id: 'spicy', name: 'Spicy', icon: 'flame' },
];

// Sort options
export const sortOptions = [
  { id: 'recommended', name: 'Recommended' },
  { id: 'price-asc', name: 'Price: Low to High' },
  { id: 'price-desc', name: 'Price: High to Low' },
  { id: 'name-asc', name: 'Name: A to Z' },
  { id: 'name-desc', name: 'Name: Z to A' },
  { id: 'popular', name: 'Most Popular' },
];

// Enhanced Menu Items with complete details
export const menuItems = [
  // STARTERS
  {
    id: 1,
    name: 'Crispy Bruschetta',
    description: 'Grilled sourdough bread topped with fresh tomatoes, basil, garlic, and extra virgin olive oil',
    shortDescription: 'Grilled sourdough bread topped with fresh tomatoes, basil, and garlic',
    ingredients: ['Sourdough bread', 'Heirloom tomatoes', 'Fresh basil', 'Garlic', 'Extra virgin olive oil', 'Balsamic glaze', 'Sea salt'],
    allergens: ['Gluten', 'Garlic'],
    price: 12,
    image: FOOD_IMAGES.bruschetta,
    category: 'starters',
    dietary: ['vegetarian'],
    popular: 85,
    tags: [],
    preparationTime: '10 min',
    seasonal: false,
    signature: false
  },
  {
    id: 2,
    name: 'Calamari Fritti',
    description: 'Lightly fried squid with lemon aioli and marinara sauce, sprinkled with parsley and lemon zest',
    shortDescription: 'Lightly fried squid with lemon aioli and marinara sauce',
    ingredients: ['Fresh squid', 'Semolina flour', 'Lemon aioli', 'Marinara sauce', 'Parsley', 'Lemon zest', 'Sea salt'],
    allergens: ['Seafood', 'Egg', 'Gluten'],
    price: 14,
    image: FOOD_IMAGES.calamari,
    category: 'starters',
    dietary: [],
    popular: 90,
    tags: ['popular'],
    preparationTime: '15 min',
    seasonal: false,
    signature: true
  },
  {
    id: 3,
    name: 'Wild Mushroom Soup',
    description: 'Creamy soup with assorted forest mushrooms, truffle oil, and herb croutons',
    shortDescription: 'Creamy soup with assorted forest mushrooms and truffle oil',
    ingredients: ['Porcini mushrooms', 'Shiitake mushrooms', 'Button mushrooms', 'Heavy cream', 'Vegetable stock', 'Truffle oil', 'Herb croutons', 'Chives'],
    allergens: ['Dairy', 'Gluten'],
    price: 10,
    image: FOOD_IMAGES.mushroom_soup,
    category: 'starters',
    dietary: ['vegetarian', 'gluten-free'],
    popular: 75,
    tags: [],
    preparationTime: '20 min',
    seasonal: true,
    signature: false
  },
  {
    id: 16,
    name: 'Burrata with Heirloom Tomatoes',
    description: 'Fresh burrata cheese with assorted heirloom tomatoes, basil oil, and aged balsamic reduction',
    shortDescription: 'Fresh burrata cheese with assorted heirloom tomatoes and balsamic',
    ingredients: ['Burrata cheese', 'Heirloom tomatoes', 'Basil oil', 'Aged balsamic vinegar', 'Microgreens', 'Sea salt', 'Black pepper'],
    allergens: ['Dairy'],
    price: 16,
    image: FOOD_IMAGES.burrata,
    category: 'starters',
    dietary: ['vegetarian', 'gluten-free'],
    popular: 95,
    tags: ['new', 'popular'],
    preparationTime: '10 min',
    seasonal: true,
    signature: true
  },
    
  // MAIN COURSES
  {
    id: 4,
    name: 'Filet Mignon',
    description: 'Prime beef tenderloin with red wine reduction, truffle mashed potatoes, and seasonal vegetables',
    shortDescription: 'Prime beef tenderloin with red wine reduction and potato purée',
    ingredients: ['Prime beef tenderloin', 'Red wine reduction', 'Truffle mashed potatoes', 'Seasonal vegetables', 'Thyme', 'Garlic butter', 'Sea salt'],
    allergens: ['Dairy'],
    price: 38,
    image: FOOD_IMAGES.steak,
    category: 'mains',
    dietary: ['gluten-free'],
    popular: 98,
    tags: ['popular', 'signature'],
    preparationTime: '30 min',
    seasonal: false,
    signature: true
  },
  {
    id: 5,
    name: 'Herb Crusted Salmon',
    description: 'Fresh Atlantic salmon with herb crust, lemon beurre blanc, served with wild rice and roasted asparagus',
    shortDescription: 'Fresh salmon with herb crust, served with seasonal vegetables',
    ingredients: ['Atlantic salmon', 'Fresh herbs', 'Panko breadcrumbs', 'Lemon beurre blanc', 'Wild rice', 'Asparagus', 'Lemon zest'],
    allergens: ['Seafood', 'Dairy', 'Gluten'],
    price: 28,
    image: FOOD_IMAGES.salmon,
    category: 'mains',
    dietary: [],
    popular: 85,
    tags: [],
    preparationTime: '25 min',
    seasonal: false,
    signature: false
  },
  {
    id: 6,
    name: 'Mushroom Risotto',
    description: 'Creamy Arborio rice with assorted mushrooms, white wine, Parmesan cheese, and fresh herbs',
    shortDescription: 'Creamy Arborio rice with assorted mushrooms and Parmesan',
    ingredients: ['Arborio rice', 'Porcini mushrooms', 'White wine', 'Parmesan cheese', 'Vegetable broth', 'Shallots', 'Thyme', 'Butter'],
    allergens: ['Dairy', 'Alcohol'],
    price: 22,
    image: FOOD_IMAGES.risotto,
    category: 'mains',
    dietary: ['vegetarian', 'gluten-free'],
    popular: 80,
    tags: [],
    preparationTime: '30 min',
    seasonal: false,
    signature: false
  },
  {
    id: 7,
    name: 'Spicy Arrabiata Pasta',
    description: 'Penne pasta with spicy tomato sauce, garlic, chili flakes, fresh basil, and vegan parmesan',
    shortDescription: 'Penne with spicy tomato sauce, garlic, and chili flakes',
    ingredients: ['Penne pasta', 'San Marzano tomatoes', 'Garlic', 'Chili flakes', 'Fresh basil', 'Vegan parmesan', 'Extra virgin olive oil'],
    allergens: ['Gluten'],
    price: 18,
    image: FOOD_IMAGES.pasta,
    category: 'mains',
    dietary: ['vegetarian', 'vegan', 'dairy-free', 'spicy'],
    popular: 75,
    tags: ['spicy'],
    preparationTime: '20 min',
    seasonal: false,
    signature: false
  },
  {
    id: 15,
    name: 'Seasonal Sushi Platter',
    description: 'Chef\'s selection of fresh sushi including nigiri, sashimi, and specialty rolls served with wasabi, pickled ginger, and soy sauce',
    shortDescription: 'Chef\'s selection of fresh sushi including nigiri, sashimi, and specialty rolls',
    ingredients: ['Fresh assorted fish', 'Sushi rice', 'Nori seaweed', 'Cucumber', 'Avocado', 'Wasabi', 'Pickled ginger', 'Soy sauce'],
    allergens: ['Seafood', 'Gluten', 'Soy'],
    price: 32,
    image: FOOD_IMAGES.sushi,
    category: 'mains',
    dietary: ['gluten-free'],
    popular: 92,
    tags: ['new', 'seasonal'],
    preparationTime: '30 min',
    seasonal: true,
    signature: true
  },
    
  // DESSERTS
  {
    id: 8,
    name: 'Chocolate Lava Cake',
    description: 'Warm chocolate cake with molten center, vanilla bean ice cream, fresh berries, and raspberry coulis',
    shortDescription: 'Warm chocolate cake with molten center and vanilla ice cream',
    ingredients: ['Dark chocolate', 'Butter', 'Eggs', 'Sugar', 'Flour', 'Vanilla bean ice cream', 'Fresh berries', 'Raspberry coulis'],
    allergens: ['Dairy', 'Eggs', 'Gluten'],
    price: 12,
    image: FOOD_IMAGES.chocolate_cake,
    category: 'desserts',
    dietary: ['vegetarian'],
    popular: 95,
    tags: ['popular', 'signature'],
    preparationTime: '15 min',
    seasonal: false,
    signature: true
  },
  {
    id: 9,
    name: 'Crème Brûlée',
    description: 'Classic vanilla custard with caramelized sugar top, served with fresh berries and mint',
    shortDescription: 'Classic vanilla custard with caramelized sugar top',
    ingredients: ['Heavy cream', 'Vanilla bean', 'Egg yolks', 'Sugar', 'Fresh berries', 'Mint leaves'],
    allergens: ['Dairy', 'Eggs'],
    price: 10,
    image: FOOD_IMAGES.creme_brulee,
    category: 'desserts',
    dietary: ['vegetarian', 'gluten-free'],
    popular: 85,
    tags: [],
    preparationTime: '20 min + cooling time',
    seasonal: false,
    signature: false
  },
  {
    id: 17,
    name: 'Classic Tiramisu',
    description: 'Traditional Italian dessert with layers of coffee-soaked ladyfingers, mascarpone cream, and cocoa powder',
    shortDescription: 'Traditional Italian dessert with coffee-soaked ladyfingers and mascarpone',
    ingredients: ['Ladyfingers', 'Mascarpone cheese', 'Espresso', 'Eggs', 'Sugar', 'Cocoa powder', 'Amaretto liqueur'],
    allergens: ['Dairy', 'Eggs', 'Gluten', 'Alcohol'],
    price: 11,
    image: FOOD_IMAGES.tiramisu,
    category: 'desserts',
    dietary: ['vegetarian'],
    popular: 90,
    tags: ['popular'],
    preparationTime: '30 min + chilling time',
    seasonal: false,
    signature: false
  },
    
  // DRINKS
  {
    id: 10,
    name: 'Signature Martini',
    description: 'House special blend with premium vodka, elderflower liqueur, fresh lime juice, and a hint of cucumber',
    shortDescription: 'House special blend with premium vodka and a secret twist',
    ingredients: ['Premium vodka', 'Elderflower liqueur', 'Fresh lime juice', 'Cucumber', 'Simple syrup', 'Ice'],
    allergens: ['Alcohol'],
    price: 14,
    image: FOOD_IMAGES.martini,
    category: 'drinks',
    dietary: ['vegan', 'gluten-free', 'dairy-free'],
    popular: 88,
    tags: ['signature'],
    preparationTime: '5 min',
    seasonal: false,
    signature: true
  },
  {
    id: 11,
    name: 'Craft Lemonade',
    description: 'Fresh-squeezed lemonade with mint, local honey, and seasonal berries',
    shortDescription: 'Fresh-squeezed lemonade with mint and local honey',
    ingredients: ['Fresh lemon juice', 'Local honey', 'Mint leaves', 'Seasonal berries', 'Sparkling water'],
    allergens: [],
    price: 6,
    image: FOOD_IMAGES.lemonade,
    category: 'drinks',
    dietary: ['vegetarian', 'vegan', 'gluten-free', 'dairy-free', 'nut-free'],
    popular: 80,
    tags: [],
    preparationTime: '5 min',
    seasonal: true,
    signature: false
  },
  {
    id: 18,
    name: 'Seasonal Berry Spritz',
    description: 'Refreshing cocktail with fresh seasonal berries, prosecco, and botanical-infused soda water',
    shortDescription: 'Refreshing cocktail with fresh seasonal berries and prosecco',
    ingredients: ['Seasonal berries', 'Prosecco', 'Botanical-infused soda', 'Elderflower syrup', 'Fresh mint', 'Ice'],
    allergens: ['Alcohol'],
    price: 13,
    image: FOOD_IMAGES.cocktail,
    category: 'drinks',
    dietary: ['vegetarian', 'vegan', 'gluten-free', 'dairy-free'],
    popular: 92,
    tags: ['seasonal', 'new'],
    preparationTime: '5 min',
    seasonal: true,
    signature: false
  }
];